### ISSUE TITLE
Graphics 

### ISSUE THREAD

**Issue by m-lin1** [The-Koopalings/Flee_The_Factory#139]
- [x] Game Elements 
     - [x] keys
     - [x] doors (the diff colors for the DS levels)
     - [x] virus
     - [x] Win Condition Lights
     - [x] Clear button
     - [x] Clear All button   
     - [x] For Loop step operator (+,-,*,/) {Needs background too, 20x24 px}
- [x] Animations
     - [x] Interact
     - [x] Death (fix animation)
- [x] Inventory
- [x] Credits scene
    - [x] Background
    - [x] Scrolling text
- [x] Stage/Level selects (same pic maybe recolored for each stage)
- [x] Settings Menu
- [x] Code blocks
    - [x] pick up item
    - [x] use item
    - [x] call while 1, 2, 3
    - [x] call for 1, 2, 3
    - [x] call F 1, 2, 3
    - [x] default call loop 1, 2, 3 before the user chooses for or while
- [x] Fonts + scaling
- [x] An arrow we can use to point to diff game components during the tutorial dialogue

**Comment by KareO2** [comment]
DONE!
