### ISSUE TITLE
Revamp code for auto puzzle generation

### ISSUE THREAD

**Issue by m-lin1** [The-Koopalings/Flee_The_Factory#60]
Change the code so that the order of Grid's child nodes do not matter for auto placing the nodes according to the grid array

This specific line probably:
![image](https://github.com/The-Koopalings/Flee_The_Factory/assets/43522378/eaf37642-e58e-4775-a090-6df932df9584)

**Comment by Okayd123** [comment]
Order of child nodes no longer matters in Grid node
Error is created during initialization when an is expected but cannot be found on the Grid.
