### ISSUE TITLE
Animate Robot Movement

### ISSUE THREAD

**Issue by Okayd123** [The-Koopalings/Flee_The_Factory#95]
Animate the movements of the robot rather than have it teleport/snap into the position and orientations. Make sure the timings fit within the execution speed of code blocks (can we LERP this?)
This is to make sure we have the structure for it once we have the fully fledged animations:

- [x] Rotation 
- [x] Forwards 
- [x] Interact (Sprite changes color then back to it's original)

**Comment by KareO2** [comment]
- instead of robot animation, it's now a Button Animation
