### ISSUE TITLE
SceneSwapper

### ISSUE THREAD

**Issue by Okayd123** [The-Koopalings/Flee_The_Factory#96]
Create a singleton (called "Scenes"?) to manage swapping between scenes. To make the use of this easier, it should be able to take in parameters to switch to a target scene. (Necessary for #94)

Godot has a tutorial for basic scene switching: https://docs.godotengine.org/en/3.5/tutorials/scripting/singletons_autoload.html

- [x] Use a map to store all scenes that can be loaded. Either preload all the scenes and store <name, scene> or just store <name, path to scene>

- [x] Handle Scene Swapping between:
   - [x] Stage Selection <-> Level selections 
   - [x] Level Selection <-> Level 
   - Should be doable in one function. Most of the work is in making is easy to figure out which scene to switch to and then load it.

**Comment by m-lin1** [comment]
Map to correct Control Flow + Recursion levels once those are made

**Comment by he-larious** [comment]
Remove hard coded level paths from the scene_path dictionary

**Comment by he-larious** [comment]
Grab the level number from the file name for the scene_path dict key
